### ISSUE TITLE
PyFerret window "Image -> Save As" fails for PNG files

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1895]
Discovered by John Lanzante at GFDL, running in RHEL7 KDE Plasma environment.  First generate a plot:

```
 	NOAA/PMEL TMAP
 	PyFerret v7.43 (optimized)
 	Linux 3.10.0-862.11.6.el7.x86_64 - 09/14/18
 	20-Sep-18 13:15     

yes? plot/vs {0,1},{0,1}
```

Now go to the PyFerret display window, and select "Image -> Save As -> ferret.png".  Instead of getting a PNG file, we get the following errors:

```
yes? kfilemodule(11210): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
kfilemodule(11210): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
kfilemodule(11210): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
Traceback (most recent call last):
  File "/home/k1s/PyFerretRH7-7.4.3/lib/python2.7/site-packages/pipedviewer/pipedviewerpq.py", line 651, in inquireSaveFilename
    raise RuntimeError("Unexpected file format name '%s'" % fileFilter)
RuntimeError: Unexpected file format name 'PNG - Portable Networks Graphics (*.png)' 
```

However, the following command works fine:

```
yes? frame/file="ferret.png"
```

Apparently this did not happen in PyFerret v7.02.

**Comment by karlmsmith** [comment]
This was fixed with the commit https://github.com/NOAA-PMEL/PyFerret/commit/9e60133ce66a0204b1610eab1c74e442ffb7a498
and is in the 7.4.3.2 build at GFDL as well as the recent 7.4.4 release.

**Comment by AndrewWittenberg** [comment]
As of PyFerret v7.4.4.4, the menu can now be used to produce the plot (ferret.png).  But I still get a lot of errors popping up:
```
 	NOAA/PMEL TMAP
 	PyFerret v7.444 (optimized)
 	Linux 3.10.0-957.10.1.el7.x86_64 - 04/16/19
 	17-Apr-19 13:05     

yes? plot/vs {0,1},{0,1}
yes? kfilemodule(32577): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
kfilemodule(32577): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
kfilemodule(32577): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-visio.template.macroEnabled.main+xml" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.binary.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.addin.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-visio.drawing.macroEnabled.main+xml" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-visio.stencil.macroEnabled.main+xml" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.presentation.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.template.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.template.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.template.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.document.macroEnabled.12" 
kfilemodule(32577) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slide.macroEnabled.12" 
kfilemodule(32577): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
yes? 
```

**Comment by eugeneburger** [comment]
Issue specific to andrew's environment - chat with Karl 06/15/20
